debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace # db ? ??? ????? ?? ?????? ?????

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: kim
    password: thisisTESTpw!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true # ???? ?????? ??? ?????
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated # 데이터 리포지토리를 API에 노출시킬지에 대한 전략 설정  annotated : 에노테이션으로 지정한 것만 노출
  thymeleaf3:
    decoupled-logic: true


#
#---
#
#spring:
#  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none # @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE) 와 같은 효과를 전역으로 사용하기 위해